#Define your project's libraries and source files here.
#This section is compulsory.
Libraries:
    # Sources
    - name: src
      paths:
        - "./src/*.vhdl"
        - "./src/*.vhd"

    # Test benches
    - name: tb
      paths:
        - "./tb/*.vhdl"
        - "./tb/*.vhd"

    # Common library
    - name: com_lib
      paths:
        - "./lib/*.vhd"
        - "./lib/*.vhdl"

    - name: root_common_lib
      paths:
        - "../../lib/*.vhd"
        - "../../lib/*.vhdl"
        - "../../lib/**/*.vhd"
        - "../../lib/**/*.vhdl"

    #Point to the IEEE standard libraries
    - name: ieee
      paths:
        - "C:/intelFPGA_lite/20.1/quartus/libraries/vhdl/**/*.vhd"
        - "C:/intelFPGA_lite/20.1/quartus/libraries/vhdl/**/**/*.vhd"

Preferences:
    #Enable/disable typechecking
    TypeCheck: True


    #Display errors over multiple lines
    MultiLineErrors: True


    #Enable/disable check-as-you-type
    CheckOnChange: True


    #Enable/disable linting
    Lint: True


    #Display the first sintax error only in a file
    FirstSyntaxErrorOnly: True


#Linter rule configuration.
#Rules can be enabled or disabled.
#Rules also have a severity. It may be one of Info, Warning, Critical or Error.
Lint:
    #Threshold, below which messages are not displayed.
    Threshold: Warning


    #Long form rule configuration. Both enabled/disabled status and severity can be configured this way.
    DeclaredNotAssigned:
        enabled:  True
        severity: Warning #Default severity Warning


    #Short form. Only enabled/disabled status can be specified. Severity is the default for the rule.
    DeclaredNotRead:             True #Default severity Warning
    ReadNotAssigned:             True #Default severity Critical
    SensitivityListCheck:        True #Default severity Warning
    ExtraSensitivityListCheck:   True #Default severity Warning
    DuplicateSensitivity:        True #Default severity Warning
    LatchCheck:                  True #Default severity Critical
    VariableNotRead:             True #Default severity Warning
    VariableNotWritten:          True #Default severity Warning
    PortNotRead:                 True #Default severity Warning
    PortNotWritten:              True #Default severity Critical
    NoPrimaryUnit:               True #Default severity Warning
    DuplicateLibraryImport:      True #Default severity Warning
    DuplicatePackageUsage:       True #Default severity Warning
    DeprecatedPackages:          True #Default severity Warning
    ImplicitLibraries:           True #Default severity Warning
    DisconnectedPorts:           True #Default severity Critical
    IntNoRange:                  True #Default severity Warning